### ISSUE TITLE
Second generation of training fails

### ISSUE THREAD

**Issue by m3lodyp0nd** [doctor-diebo/tictactoe-ai#3]
`Traceback (most recent call last):
  File "train.py", line 13, in <module>
    test.naturalSelection()
  File "/home/dieb/tictactoe-ai/population.py", line 69, in naturalSelection
    new_networks[i] = parent.getBaby()
AttributeError: 'NoneType' object has no attribute 'getBaby'`

entire output: https://pastebin.com/LKFgSJ72

Suspected issue: getBaby() isn't returning a Network object

**Comment by doctor-diebo** [comment]
Not necessary anymore, complete redesign
